// Command lifecyclediagram renders the standalone-activity lifecycle as a d2 diagram, derived
// entirely from saaspec.Model — the same executable spec the conformance tests check the real server
// against. It prints d2 to stdout. Regenerate the committed .d2/.svg via `make saa-lifecycle-diagram`;
// never hand-edit the output. Because every cell is computed from Model(), the diagram cannot drift
// from the spec (e.g. it says start_delay is "not updateable" once dispatched, because Model rejects
// it there — a hand-drawn diagram got that wrong).
package main

import (
	"fmt"
	"os"
	"strings"

	"go.temporal.io/server/chasm/lib/activity/saaspec"
)

// The activity configuration the diagram is drawn for: a start_delay on the first attempt and
// unlimited retries, so the canonical trace shows attempt 1 retrying and attempt 2 completing.
var cfg = saaspec.Config{HasStartDelay: true}

// Fills encode the semantic category of a cell (see legend), not arbitrary decoration.
const (
	fillImmediate  = "#cde7cd" // the operation takes effect immediately
	fillDeferred   = "#ffe6bf" // accepted but deferred: a request resolved at the next attempt boundary
	fillBlocked    = "#e8e8e8" // not permitted in this phase
	fillInfo       = "#f4f4f4" // informational (the active timer)
	fillLabel      = "#e0e0e0" // row/column headers
	fillScheduled  = "#dbe9ff"
	fillDispatched = "#ece3f7"
	fillStarted    = "#cde7cd"
	fillTerminal   = "#e0e0e0"
)

type cell struct {
	label string
	fill  string
	bold  bool
}

func immediate(l string) cell { return cell{l, fillImmediate, false} }
func deferred(l string) cell  { return cell{l, fillDeferred, false} }
func blocked() cell           { return cell{"—", fillBlocked, false} }

func main() {
	phases := canonicalTrace()

	rows := []struct {
		name string
		fn   func(saaspec.AbstractState) cell
	}{
		{"active timer", timerCell},
		{"pause", pauseCell},
		{"unpause\n(if paused)", unpauseCell},
		{"update\nstart_delay", updateStartDelayCell},
		{"cancel", cancelCell},
		{"reset", resetCell},
		{"terminate", terminateCell},
	}

	var b strings.Builder
	b.WriteString("# GENERATED by `make saa-lifecycle-diagram` from saaspec.Model — do not edit.\n\n")
	b.WriteString("page: \"\" {\n")
	b.WriteString("  grid-rows: 3\n")
	b.WriteString("  grid-gap: 25\n")
	b.WriteString("  style.stroke-width: 0\n\n")

	// Title.
	b.WriteString("  title: \"Standalone Activity — lifecycle & operations\\n(generated from saaspec.Model; the spec the conformance tests check the server against)\" {\n")
	b.WriteString("    style.bold: true\n    style.font-size: 22\n    style.stroke-width: 0\n  }\n\n")

	// Table: columns = label column + one per phase (left→right is time); rows = header + one per
	// operation. grid-rows is declared first so d2 fills row-major (the dominant keyword wins).
	ncol := len(phases) + 1
	nrow := len(rows) + 1
	b.WriteString("  table: \"\" {\n")
	b.WriteString(fmt.Sprintf("    grid-rows: %d\n", nrow))
	b.WriteString(fmt.Sprintf("    grid-columns: %d\n", ncol))
	b.WriteString("    grid-gap: 0\n\n")

	emit := func(r, c int, cl cell) {
		attrs := []string{fmt.Sprintf("style.fill: \"%s\"", cl.fill)}
		if cl.bold {
			attrs = append(attrs, "style.bold: true")
		}
		fmt.Fprintf(&b, "    c%d_%d: \"%s\" { %s }\n", r, c, d2Label(cl.label), strings.Join(attrs, "; "))
	}

	// Header row: corner + milestone per phase.
	emit(0, 0, cell{"operation  ↓\nphase / time  →", fillLabel, true})
	for i, s := range phases {
		emit(0, i+1, milestoneCell(s))
	}
	// One row per operation.
	for r, row := range rows {
		emit(r+1, 0, cell{row.name, fillLabel, true})
		for i, s := range phases {
			emit(r+1, i+1, row.fn(s))
		}
	}
	b.WriteString("  }\n\n")

	// Legend.
	b.WriteString("  legend: \"\" {\n    grid-columns: 3\n    grid-gap: 0\n")
	fmt.Fprintf(&b, "    l0: \"immediate effect\" { style.fill: \"%s\" }\n", fillImmediate)
	fmt.Fprintf(&b, "    l1: \"accepted but deferred (request resolved at the next attempt boundary)\" { style.fill: \"%s\" }\n", fillDeferred)
	fmt.Fprintf(&b, "    l2: \"not permitted\" { style.fill: \"%s\" }\n", fillBlocked)
	b.WriteString("  }\n")

	b.WriteString("}\n")

	fmt.Print(b.String())
}

// canonicalTrace drives Model through the happy-path-with-one-retry that the diagram visualizes:
// SCHEDULED(start delay) → dispatched → STARTED → SCHEDULED(retry backoff) → dispatched → STARTED →
// COMPLETED. The states passed through become the columns.
func canonicalTrace() []saaspec.AbstractState {
	advance := []saaspec.Event{
		{Kind: saaspec.StartDelayElapses},              // start delay elapses -> dispatchable
		{Kind: saaspec.Poll},                           // worker picks it up -> STARTED
		{Kind: saaspec.RespondFailed, Retryable: true}, // attempt 1 fails -> retry backoff
		{Kind: saaspec.BackoffElapses},                 // backoff elapses -> dispatchable
		{Kind: saaspec.Poll},                           // worker picks it up -> STARTED (attempt 2)
	}
	phases := []saaspec.AbstractState{saaspec.Initial(cfg)}
	for _, e := range advance {
		phases = append(phases, saaspec.Model(cfg, phases[len(phases)-1], e).Next)
	}
	end := saaspec.Model(cfg, phases[len(phases)-1], saaspec.Event{Kind: saaspec.RespondCompleted}).Next
	if end.Status != saaspec.Completed {
		fmt.Fprintf(os.Stderr, "lifecyclediagram: canonical trace does not complete (ended %s); spec changed?\n", end.Status)
		os.Exit(1)
	}
	return append(phases, end)
}

func milestoneCell(s saaspec.AbstractState) cell {
	var label, fill string
	switch {
	case s.Status == saaspec.Scheduled && s.Dispatchability == saaspec.Dispatchable:
		label, fill = "dispatched", fillDispatched
	case s.Status == saaspec.Scheduled:
		label, fill = "SCHEDULED", fillScheduled
	case s.Status == saaspec.Started:
		label, fill = "STARTED", fillStarted
	default:
		label, fill = strings.ToUpper(s.Status.String()), fillTerminal
	}
	if !s.Status.Terminal() {
		label += fmt.Sprintf("\nattempt %d", s.Count)
	}
	return cell{label, fill, true}
}

func timerCell(s saaspec.AbstractState) cell {
	switch {
	case s.Status == saaspec.Scheduled && s.Dispatchability == saaspec.StartDelayPending:
		return cell{"start delay", fillInfo, false}
	case s.Status == saaspec.Scheduled && s.Dispatchability == saaspec.BackoffPending:
		return cell{"retry backoff", fillInfo, false}
	case s.Status == saaspec.Scheduled && s.Dispatchability == saaspec.Dispatchable:
		return cell{"schedule-to-start", fillInfo, false}
	case s.Status == saaspec.Started:
		return cell{"start-to-close\n+ heartbeat", fillInfo, false}
	default:
		return cell{"—", fillInfo, false}
	}
}

func pauseCell(s saaspec.AbstractState) cell {
	out := saaspec.Model(cfg, s, saaspec.Event{Kind: saaspec.Pause})
	if out.Reject != saaspec.NoError {
		return blocked()
	}
	switch out.Next.Status {
	case saaspec.Paused:
		return immediate("pausable")
	case saaspec.PauseRequested:
		return deferred("pause\nrequestable")
	default:
		return blocked()
	}
}

func unpauseCell(s saaspec.AbstractState) cell {
	p := saaspec.Model(cfg, s, saaspec.Event{Kind: saaspec.Pause})
	if p.Reject != saaspec.NoError { // not pausable here, so "if paused" is vacuous
		return blocked()
	}
	n := saaspec.Model(cfg, p.Next, saaspec.Event{Kind: saaspec.Unpause}).Next
	switch {
	case n.Status == saaspec.Started:
		return immediate("removes\npause request")
	case n.Status == saaspec.Scheduled && n.Dispatchability == saaspec.Dispatchable:
		return immediate("dispatches\nimmediately")
	case n.Dispatchability == saaspec.StartDelayPending:
		return deferred("dispatches at end\nof start delay")
	case n.Dispatchability == saaspec.BackoffPending:
		return deferred("dispatches at end\nof retry backoff")
	default:
		return blocked()
	}
}

func updateStartDelayCell(s saaspec.AbstractState) cell {
	out := saaspec.Model(cfg, s, saaspec.Event{Kind: saaspec.UpdateOptions, SetsStartDelay: true})
	if out.Reject != saaspec.NoError {
		return cell{"not updateable", fillBlocked, false}
	}
	return immediate("updateable")
}

func cancelCell(s saaspec.AbstractState) cell {
	out := saaspec.Model(cfg, s, saaspec.Event{Kind: saaspec.RequestCancel})
	if out.Reject != saaspec.NoError {
		return blocked()
	}
	switch out.Next.Status {
	case saaspec.Canceled:
		return immediate("cancellable")
	case saaspec.CancelRequested:
		return deferred("cancel\nrequestable")
	default:
		return blocked()
	}
}

func resetCell(s saaspec.AbstractState) cell {
	out := saaspec.Model(cfg, s, saaspec.Event{Kind: saaspec.Reset})
	if out.Reject != saaspec.NoError {
		return blocked()
	}
	if out.Next.Status == saaspec.ResetRequested {
		return deferred("reset\nrequestable")
	}
	return immediate("resettable")
}

func terminateCell(s saaspec.AbstractState) cell {
	out := saaspec.Model(cfg, s, saaspec.Event{Kind: saaspec.Terminate})
	if out.Reject == saaspec.NoError && out.Next.Status == saaspec.Terminated {
		return immediate("→ Terminated")
	}
	return blocked()
}

// d2Label renders a multi-line cell label as a d2 double-quoted string (newlines become \n).
func d2Label(s string) string { return strings.ReplaceAll(s, "\n", `\n`) }
