// Command saainteractive derives the data for the interactive standalone-activity page from the SAA
// behavior spec.
//
// Like saaanim, it encodes no product behavior of its own: every reachable state, per-operation
// classification, transition target, attempt-boundary outcome, and timer anchor is obtained by
// executing saaspec.Model / Initial / ExpectedDescribe and the shared spec-derived view-model in
// ../../lifecycle. The web page performs only presentation, timeline geometry, and lookups into the
// table emitted here; it contains no behavior rules.
//
// Output is a plain JS file assigning a global (so the page loads over file:// without fetch/CORS),
// and, optionally, the same payload as raw JSON.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"go.temporal.io/server/chasm/lib/activity/saaspec"
	"go.temporal.io/server/chasm/lib/activity/saaspec/lifecycle"
)

func main() {
	jsOut := flag.String("o", "", "output .js path (assigns window.SAA_SPEC); default stdout")
	jsonOut := flag.String("json", "", "also write raw JSON to this path")
	flag.Parse()

	data := build()
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		fatal(err)
	}
	if *jsonOut != "" {
		if err := os.WriteFile(*jsonOut, body, 0o644); err != nil {
			fatal(err)
		}
	}
	src := "// AUTO-GENERATED by saainteractive from saaspec.Model — do not edit.\n" +
		"// Every value below is a projection of the executable spec.\n" +
		"window.SAA_SPEC = " + string(body) + ";\n"
	w := os.Stdout
	if *jsOut != "" {
		f, err := os.Create(*jsOut)
		if err != nil {
			fatal(err)
		}
		defer f.Close()
		w = f
	}
	if _, err := fmt.Fprint(w, src); err != nil {
		fatal(err)
	}
}

func fatal(err error) { fmt.Fprintln(os.Stderr, "saainteractive:", err); os.Exit(1) }

// --- output shape ---

type opView struct {
	Name     string `json:"name"`
	Label    string `json:"label"`
	Category string `json:"category"` // NotPermitted | Immediate | Deferred
	Next     int    `json:"next"`     // resulting state id (== id when rejected/self-loop)
	Reject   string `json:"reject"`   // error name, or ""
	SelfLoop bool   `json:"selfLoop"`
}

type eventView struct {
	Kind   string `json:"kind"`
	Label  string `json:"label"`
	Group  string `json:"group"` // dispatch | attemptEnd
	Next   int    `json:"next"`
	Reject string `json:"reject"`
	Noop   bool   `json:"noop"`
}

type stateView struct {
	ID              int         `json:"id"`
	Status          string      `json:"status"`
	Dispatchability string      `json:"dispatchability"`
	Count           int32       `json:"count"`
	Milestone       string      `json:"milestone"`
	Timer           string      `json:"timer"`
	Terminal        bool        `json:"terminal"`
	PendingRequest  string      `json:"pendingRequest"` // pause|cancel|reset|"" (display projection of status)
	DescribeStatus  string      `json:"describeStatus"`
	DescribePending string      `json:"describePending"`
	Ops             []opView    `json:"ops"`
	Events          []eventView `json:"events"`
}

type timerView struct {
	Name   string `json:"name"`
	Anchor string `json:"anchor"` // schedule | firstDispatch | attempt — derived by probing the spec
}

type phaseView struct {
	StateID   int    `json:"stateId"`
	Milestone string `json:"milestone"`
	Timer     string `json:"timer"`
	Attempt   int32  `json:"attempt"`
	Terminal  bool   `json:"terminal"`
}

type configView struct {
	HasScheduleToClose bool  `json:"hasScheduleToClose"`
	HasScheduleToStart bool  `json:"hasScheduleToStart"`
	HasHeartbeat       bool  `json:"hasHeartbeat"`
	HasStartDelay      bool  `json:"hasStartDelay"`
	MaxAttempts        int32 `json:"maxAttempts"`
}

type data struct {
	Cfg              configView     `json:"cfg"`
	States           []stateView    `json:"states"`
	InitialWithDelay int            `json:"initialWithDelay"`
	InitialNoDelay   int            `json:"initialNoDelay"`
	Canonical        []phaseView    `json:"canonical"`
	Timers           []timerView    `json:"timers"`
	AttemptStates    map[string]int `json:"attemptStates"`   // status -> representative live-attempt state id
	AttemptEndOrder  []string       `json:"attemptEndOrder"` // event kinds in display order
}

// --- driving inputs ---

// cfg enables every feature with a small attempt cap so the reachable graph contains both the retry
// edge (Count < Max) and the terminal-failure edge (Count == Max), and both the StartDelayPending
// initial state and its Dispatchable successor.
var cfg = saaspec.Config{
	HasScheduleToClose: true, HasScheduleToStart: true, HasHeartbeat: true, HasStartDelay: true,
	MaxAttempts: 3,
}

// opEvents pairs each classified operation with the event driven to compute its transition target.
// The category/label come from lifecycle.Classify; the Next state comes from Model.
var opEvents = map[string]saaspec.Event{
	"pause":               {Kind: saaspec.Pause},
	"unpause (if paused)": {Kind: saaspec.Unpause},
	"update start_delay":  {Kind: saaspec.UpdateOptions, SetsStartDelay: true},
	"cancel":              {Kind: saaspec.RequestCancel},
	"reset":               {Kind: saaspec.Reset},
	"terminate":           {Kind: saaspec.Terminate},
}

type labeledEvent struct {
	kind  saaspec.EventKind
	label string
	group string
	event saaspec.Event
}

var dispatchEvents = []labeledEvent{
	{saaspec.StartDelayElapses, "start delay elapses", "dispatch", saaspec.Event{Kind: saaspec.StartDelayElapses}},
	{saaspec.BackoffElapses, "retry backoff elapses", "dispatch", saaspec.Event{Kind: saaspec.BackoffElapses}},
	{saaspec.Poll, "worker poll (dispatch)", "dispatch", saaspec.Event{Kind: saaspec.Poll}},
	{saaspec.ScheduleToStartElapses, "schedule-to-start elapses", "dispatch", saaspec.Event{Kind: saaspec.ScheduleToStartElapses}},
	{saaspec.ScheduleToCloseElapses, "schedule-to-close elapses", "dispatch", saaspec.Event{Kind: saaspec.ScheduleToCloseElapses}},
}

var attemptEndEvents = []labeledEvent{
	{saaspec.RespondCompleted, "RespondCompleted", "attemptEnd", saaspec.Event{Kind: saaspec.RespondCompleted}},
	{saaspec.RespondFailed, "RespondFailed (retryable)", "attemptEnd", saaspec.Event{Kind: saaspec.RespondFailed, Retryable: true}},
	{saaspec.RespondFailed, "RespondFailed (non-retryable)", "attemptEnd", saaspec.Event{Kind: saaspec.RespondFailed}},
	{saaspec.RespondCanceled, "RespondCanceled", "attemptEnd", saaspec.Event{Kind: saaspec.RespondCanceled}},
	{saaspec.StartToCloseElapses, "start-to-close elapses", "attemptEnd", saaspec.Event{Kind: saaspec.StartToCloseElapses}},
	{saaspec.HeartbeatElapses, "heartbeat elapses", "attemptEnd", saaspec.Event{Kind: saaspec.HeartbeatElapses}},
}

// --- construction ---

func build() data {
	states := lifecycle.Reachable(cfg)
	id := make(map[saaspec.AbstractState]int, len(states))
	for i, s := range states {
		id[s] = i
	}
	idOf := func(s saaspec.AbstractState) int {
		i, ok := id[s]
		if !ok {
			fatal(fmt.Errorf("state not in reachable set: %+v", s))
		}
		return i
	}

	views := make([]stateView, len(states))
	for i, s := range states {
		views[i] = buildState(i, s, idOf)
	}

	return data{
		Cfg:              cfgView(cfg),
		States:           views,
		InitialWithDelay: idOf(saaspec.Initial(cfg)),
		InitialNoDelay:   idOf(saaspec.Initial(cfgNoDelay())),
		Canonical:        buildCanonical(idOf),
		Timers:           buildTimers(),
		AttemptStates:    buildAttemptStates(states),
		AttemptEndOrder:  attemptEndLabels(),
	}
}

func buildState(i int, s saaspec.AbstractState, idOf func(saaspec.AbstractState) int) stateView {
	ds, dp := saaspec.ExpectedDescribe(s)
	v := stateView{
		ID:              i,
		Status:          s.Status.String(),
		Dispatchability: s.Dispatchability.String(),
		Count:           s.Count,
		Milestone:       lifecycle.Milestone(s),
		Timer:           lifecycle.Timer(s),
		Terminal:        s.Status.Terminal(),
		PendingRequest:  pendingRequest(s.Status),
		DescribeStatus:  ds.String(),
		DescribePending: dp.String(),
	}
	for _, op := range lifecycle.Ops {
		cell := op.Classify(cfg, s)
		out := saaspec.Model(cfg, s, opEvents[op.Name])
		v.Ops = append(v.Ops, opView{
			Name:     op.Name,
			Label:    cell.Label,
			Category: categoryName(cell.Category),
			Next:     idOf(out.Next),
			Reject:   lifecycle.ErrorName(out.Reject),
			SelfLoop: out.Next == s,
		})
	}
	for _, le := range append(append([]labeledEvent{}, dispatchEvents...), attemptEndEvents...) {
		out := saaspec.Model(cfg, s, le.event)
		v.Events = append(v.Events, eventView{
			Kind:   le.label,
			Label:  le.label,
			Group:  le.group,
			Next:   idOf(out.Next),
			Reject: lifecycle.ErrorName(out.Reject),
			Noop:   out.Reject == saaspec.NoError && out.Next == s,
		})
	}
	return v
}

func buildCanonical(idOf func(saaspec.AbstractState) int) []phaseView {
	phases := lifecycle.CanonicalTrace(cfg)
	out := make([]phaseView, len(phases))
	for i, p := range phases {
		out[i] = phaseView{
			StateID:   idOf(p.State),
			Milestone: p.Milestone,
			Timer:     p.Timer,
			Attempt:   p.Attempt,
			Terminal:  p.Terminal,
		}
	}
	return out
}

// buildTimers derives each timeout's anchor by probing the spec: does the corresponding *Elapses
// event no-op while the first dispatch is still pending (StartDelayPending)? If so the timer does not
// run during the start delay, i.e. it is anchored at first dispatch (schedule_time + start_delay).
func buildTimers() []timerView {
	pending := saaspec.Initial(cfg) // StartDelayPending, Scheduled
	anchor := func(k saaspec.EventKind) string {
		out := saaspec.Model(cfg, pending, saaspec.Event{Kind: k})
		if out.Reject == saaspec.NoError && out.Next == pending {
			return "firstDispatch" // stale during the start delay -> not counting yet
		}
		return "schedule"
	}
	return []timerView{
		{"start delay", "schedule"},
		{"schedule-to-start", anchor(saaspec.ScheduleToStartElapses)},
		{"schedule-to-close", anchor(saaspec.ScheduleToCloseElapses)},
		{"start-to-close", "attempt"},
	}
}

// buildAttemptStates picks a representative reachable state for each live-attempt status, so the page
// can render the attempt-boundary contrast (pending request vs none) as a pure lookup.
func buildAttemptStates(states []saaspec.AbstractState) map[string]int {
	want := []saaspec.Status{saaspec.Started, saaspec.PauseRequested, saaspec.CancelRequested, saaspec.ResetRequested}
	out := map[string]int{}
	for _, st := range want {
		for i, s := range states {
			if s.Status == st {
				out[st.String()] = i
				break
			}
		}
	}
	return out
}

func attemptEndLabels() []string {
	out := make([]string, len(attemptEndEvents))
	for i, le := range attemptEndEvents {
		out[i] = le.label
	}
	return out
}

func cfgNoDelay() saaspec.Config { c := cfg; c.HasStartDelay = false; return c }

func categoryName(c lifecycle.Category) string {
	switch c {
	case lifecycle.Immediate:
		return "Immediate"
	case lifecycle.Deferred:
		return "Deferred"
	default:
		return "NotPermitted"
	}
}

func pendingRequest(st saaspec.Status) string {
	switch st {
	case saaspec.PauseRequested:
		return "pause"
	case saaspec.CancelRequested:
		return "cancel"
	case saaspec.ResetRequested:
		return "reset"
	default:
		return ""
	}
}

func cfgView(c saaspec.Config) configView {
	return configView{c.HasScheduleToClose, c.HasScheduleToStart, c.HasHeartbeat, c.HasStartDelay, c.MaxAttempts}
}
