// Command saadiagram renders the standalone-activity lifecycle as a d2 diagram. It is a thin renderer
// over the shared, spec-derived view-model in ../../lifecycle; it authors only presentation (colors,
// layout) and prints d2 to stdout. Regenerate the committed .d2/.svg via `make saa-lifecycle-diagram`.
package main

import (
	"fmt"
	"os"
	"strings"

	"go.temporal.io/server/chasm/lib/activity/saaspec"
	"go.temporal.io/server/chasm/lib/activity/saaspec/projections/lifecycle"
)

// cfg: a start_delay on the first attempt (so the start-delay phase appears) and unlimited retries,
// so the canonical trace shows attempt 1 retrying and attempt 2 completing.
var cfg = saaspec.Config{HasStartDelay: true}

// Fills encode a cell's category (see legend), not arbitrary decoration.
const (
	fillImmediate  = "#cde7cd"
	fillDeferred   = "#ffe6bf"
	fillBlocked    = "#e8e8e8"
	fillInfo       = "#f4f4f4"
	fillLabel      = "#e0e0e0"
	fillScheduled  = "#dbe9ff"
	fillDispatched = "#ece3f7"
	fillStarted    = "#cde7cd"
	fillTerminal   = "#e0e0e0"
)

func categoryFill(c lifecycle.Category) string {
	switch c {
	case lifecycle.Immediate:
		return fillImmediate
	case lifecycle.Deferred:
		return fillDeferred
	default:
		return fillBlocked
	}
}

func milestoneFill(s saaspec.AbstractState) string {
	switch {
	case s.Status == saaspec.Scheduled && s.Dispatchability == saaspec.Dispatchable:
		return fillDispatched
	case s.Status == saaspec.Scheduled:
		return fillScheduled
	case s.Status == saaspec.Started:
		return fillStarted
	default:
		return fillTerminal
	}
}

func main() {
	phases := lifecycle.CanonicalTrace(cfg)

	var b strings.Builder
	b.WriteString("# GENERATED by `make saa-lifecycle-diagram` from saaspec.Model — do not edit.\n\n")
	b.WriteString("page: \"\" {\n")
	b.WriteString("  grid-rows: 3\n")
	b.WriteString("  grid-gap: 25\n")
	b.WriteString("  style.stroke-width: 0\n\n")

	b.WriteString("  title: \"Standalone Activity — lifecycle & operations\\n(generated from saaspec.Model; the spec the conformance tests check the server against)\" {\n")
	b.WriteString("    style.bold: true\n    style.font-size: 22\n    style.stroke-width: 0\n  }\n\n")

	// Table: columns = label column + one per phase (left→right is time); rows = header + timer + one
	// per operation. grid-rows first so d2 fills row-major (the dominant keyword wins).
	ncol := len(phases) + 1
	nrow := len(lifecycle.Ops) + 2
	b.WriteString("  table: \"\" {\n")
	fmt.Fprintf(&b, "    grid-rows: %d\n", nrow)
	fmt.Fprintf(&b, "    grid-columns: %d\n", ncol)
	b.WriteString("    grid-gap: 0\n\n")

	emit := func(r, c int, label, fill string, bold bool) {
		attrs := []string{fmt.Sprintf("style.fill: \"%s\"", fill)}
		if bold {
			attrs = append(attrs, "style.bold: true")
		}
		fmt.Fprintf(&b, "    c%d_%d: \"%s\" { %s }\n", r, c, d2Label(label), strings.Join(attrs, "; "))
	}

	// Header row: corner + milestone per phase.
	emit(0, 0, "operation  ↓\nphase / time  →", fillLabel, true)
	for i, p := range phases {
		label := p.Milestone
		if !p.Terminal {
			label += fmt.Sprintf("\nattempt %d", p.Attempt)
		}
		emit(0, i+1, label, milestoneFill(p.State), true)
	}
	// Timer row.
	emit(1, 0, "active timer", fillLabel, true)
	for i, p := range phases {
		label := p.Timer
		if label == "" {
			label = "—"
		}
		emit(1, i+1, label, fillInfo, false)
	}
	// One row per operation.
	for r, op := range lifecycle.Ops {
		emit(r+2, 0, op.Name, fillLabel, true)
		for i, p := range phases {
			cell := op.Classify(cfg, p.State)
			emit(r+2, i+1, cell.Label, categoryFill(cell.Category), false)
		}
	}
	b.WriteString("  }\n\n")

	// Legend.
	b.WriteString("  legend: \"\" {\n    grid-columns: 3\n    grid-gap: 0\n")
	fmt.Fprintf(&b, "    l0: \"immediate effect\" { style.fill: \"%s\" }\n", fillImmediate)
	fmt.Fprintf(&b, "    l1: \"accepted but deferred (request resolved at the next attempt boundary)\" { style.fill: \"%s\" }\n", fillDeferred)
	fmt.Fprintf(&b, "    l2: \"not permitted\" { style.fill: \"%s\" }\n", fillBlocked)
	b.WriteString("  }\n")

	b.WriteString("}\n")

	if _, err := fmt.Print(b.String()); err != nil {
		fmt.Fprintln(os.Stderr, "saadiagram:", err)
		os.Exit(1)
	}
}

// d2Label renders a multi-line cell label as a d2 double-quoted string (newlines become \n).
func d2Label(s string) string { return strings.ReplaceAll(s, "\n", `\n`) }
